name: Docker Build

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/tds-virtual-ta:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/tds-virtual-ta:${{ github.ref_name }}
